trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: Build
  jobs:
  - job: FirstJob
    steps: 
    - bash: echo Build FristJob
    - bash: echo $(Pipeline_level_Variable)
  - job: SecoundJob
    steps: 
    - bash: echo Build SecoundJob 

- stage: DevDeploy
  variables:
    evironment_Dev: Dev
  dependsOn: Build
  jobs:
  - job: DevDeploy
    steps: 
    - bash: echo $(evironment_Dev) DevDeploy

- stage: QADeploy
  variables:
    evironment_QA: QA
  dependsOn: Build
  jobs:
  - job: QADeploy
    steps: 
    - bash: echo $(evironment_QA) QADeploy

- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeploy
    steps: 
    - bash: echo Build ProdDeploy


