trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: Build
  jobs:
  - job: FirstJob
    steps: 
    - bash: echo Build FristJob
  - job: SecoundJob
    steps: 
    - bash: echo Build SecoundJob 

- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeploy
    steps: 
    - bash: echo Build DevDeploy

- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeploy
    steps: 
    - bash: echo Build QADeploy

- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeploy
    steps: 
    - bash: echo Build ProdDeploy


