trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: Build
  jobs:
  - job: FirstJob
    steps: 
    - bash: echo Build FristJob
    - bash: echo $(Build.BuildNumber)        # gives build number 
    - bash: echo $(Build.BuildNumber)        # gives build Id
    - bash: echo $(Build.Repository.Name)    #The name of the triggering repository
    - bash: echo $(Build.SourceBranch)       #The branch of the triggering repo the build was queued
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: java --version
    - bash: node --version
    - bash: ls -R $(Build.ArtifactStagingDirectory)

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.ymal
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)




